name: "Cinema 4D Integration Tests (Fork Pilot)"

on:
  workflow_dispatch: {}
  push:
    branches:
      - ci-pilot

jobs:
  windows:
    uses: ./.github/workflows/integ_windows.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  macos:
    uses: ./.github/workflows/integ_macos.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
